// <auto-generated />
using System;
using LightOffSchedule.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LightOffSchedule.Data.Migrations
{
    [DbContext(typeof(LightOffScheduleContext))]
    [Migration("20240804165347_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("LightOffSchedule.Data.Entities.LightOffScheduleEntity", b =>
                {
                    b.Property<int>("GroupNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupNumber");

                    b.ToTable("LightOffSchedules");
                });

            modelBuilder.Entity("LightOffSchedule.Data.Entities.LightOffScheduleIntervalEntity", b =>
                {
                    b.Property<TimeSpan>("Start")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("End")
                        .HasColumnType("TEXT");

                    b.Property<int>("LightOffScheduleEntityGroupNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Start", "End", "LightOffScheduleEntityGroupNumber");

                    b.HasIndex("LightOffScheduleEntityGroupNumber");

                    b.ToTable("LightOffScheduleIntervals");
                });

            modelBuilder.Entity("LightOffSchedule.Data.Entities.LightOffScheduleIntervalEntity", b =>
                {
                    b.HasOne("LightOffSchedule.Data.Entities.LightOffScheduleEntity", "LightOffScheduleEntity")
                        .WithMany("Intervals")
                        .HasForeignKey("LightOffScheduleEntityGroupNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LightOffScheduleEntity");
                });

            modelBuilder.Entity("LightOffSchedule.Data.Entities.LightOffScheduleEntity", b =>
                {
                    b.Navigation("Intervals");
                });
#pragma warning restore 612, 618
        }
    }
}
